church_scheduling_system/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from users import views as user_views

urlpatterns = [
    path('', include('schedule_calendar.urls')),
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'),
         name='password_reset'),
    path('password-reset/done', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset-complete',
         auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
    path('schedules/', include('schedule_calendar.urls')),
]

schedule_calendar/urls.py
from django.contrib import admin
from django.urls import path
from .views import ScheduleListView, ScheduleCreateView, ScheduleDeleteView, \
    PreacherListView, PreacherUpdateView, PreacherCreateView, PreacherDeleteView, \
    ChurchListView, ChurchUpdateView, ChurchCreateView, ChurchDeleteView, \
    EventListView, EventUpdateView, EventCreateView, EventDeleteView
from . import views

urlpatterns = [
    path('', ScheduleListView.as_view(), name='schedules'),
    path('schedules/<int:schedule_id>/view/', views.schedule_update, name='schedule_update'),
    path('schedules/edit/', views.get_form, name='get_form'),
    path('schedules/<int:schedule_id>/export/', views.excel_view, name='excel_view'),
    path('schedules/<int:pk>/delete/', ScheduleDeleteView.as_view(), name='schedule_delete'),
    path('schedules/new/', ScheduleCreateView.as_view(), name='schedule_create'),
    path('preacher_list/new/', PreacherCreateView.as_view(), name='preacher_form'),
    path('preacher_list/<int:pk>/update/', PreacherUpdateView.as_view(), name='preacher_update'),
    path('preacher_list/<int:pk>/delete/', PreacherDeleteView.as_view(), name='preacher_delete'),
    path('preacher_list/', PreacherListView.as_view(), name='preacher_list'),
    path('church_list/new/', ChurchCreateView.as_view(), name='church_form'),
    path('church_list/<int:pk>/update/', ChurchUpdateView.as_view(), name='church_update'),
    path('church_list/<int:pk>/delete/', ChurchDeleteView.as_view(), name='church_delete'),
    path('church_list/', ChurchListView.as_view(), name='church_list'),
    path('event_list/new/', EventCreateView.as_view(), name='event_form'),
    path('event_list/<int:pk>/update/', EventUpdateView.as_view(), name='event_update'),
    path('event_list/<int:pk>/delete/', EventDeleteView.as_view(), name='event_delete'),
    path('event_list/', EventListView.as_view(), name='event_list'),
]

schedule_calendar/models.py
from collections import Counter

from django.contrib.postgres.fields import ArrayField
from django.db import models
from django.core.validators import RegexValidator
from django.utils.datetime_safe import strftime, time, datetime


class Schedule(models.Model):
    # Q1: September, October, November
    # Q2: December, January, February
    # Q3: March, April, May
    # Q4: June, July, August
    CHOICES = [(1, 'Q1 September - November'),
               (2, 'Q2 December - February (begins in previous year)'),
               (3, 'Q3 March - May'),
               (4, 'Q4 June - August')]

    quarter = models.IntegerField(choices=CHOICES)
    year = models.PositiveIntegerField()
    sundays = ArrayField(models.DateField(), default=list, blank=True, null=True) # Generate a list of all Sundays in the quarter when a schedule is created

    class Meta:
        unique_together = ['quarter', 'year']

    # Annoyingly have to use this property tag as you can't call date format functions in django template
    #TODO: Generate these lists when a schedule is created to avoid having to do it every time page is loaded
    # Returns a dict with month string, and int length in cells for formatting the schedule table
    @property
    def months(self):
        monthlist = list()
        for sunday in self.sundays:
            monthlist.append(sunday.strftime('%B %Y'))
        months = Counter(monthlist)
        return dict(months)

    # Returns formatted days for display in schedule table
    @property
    def dates(self):
        dates = list()
        for sunday in self.sundays:
            dates.append(sunday.strftime('%d'))
        return dates

    def __str__(self):
        if self.quarter == 1:
            return "Q" + str(self.quarter) + " " + str(self.year-1) + "-" + str(self.year)
        else:
            return "Q" + str(self.quarter) + " " + str(self.year)

class Church(models.Model):
    name = models.CharField(max_length=100)
    number = models.PositiveIntegerField()
    address = models.CharField(max_length=400)
    # Hold time here, since the morning and afternoon services for each church
    # always have the same time, unless specified in the event title
    morning_service_time = models.TimeField(auto_now=False, auto_now_add=False)
    afternoon_service_time = models.TimeField(auto_now=False, auto_now_add=False, null=True, blank=True)

    # Essentially a toString method
    def __str__(self):
        return self.name


class Preacher(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$',
                                 message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")
    phone_number = models.CharField(validators=[phone_regex], max_length=17, blank=True)
    email = models.EmailField(max_length=100, null=True, blank=True)
    num_services = models.PositiveIntegerField(null=True, blank=True, verbose_name="Number of services this preacher "
                                                                                   "would like to cover per quarter. "
                                                                                   "Leave blank to let the system determine a fair number.")
    availability = ArrayField(models.DateField(), default=list, blank=True)

    def getDates(self):
        dates = []
        for date in self.availability:
            dates.append(date.strftime("%m/%d/%Y"))
        return dates

    def __str__(self):
        if self.first_name == 'Local Arrangements':
            return self.first_name
        else:
            return self.first_name[0].upper() + '. ' + self.last_name


class Event(models.Model):

    # Hold service type here, since a service can only be either morning or afternoon
    class ServiceType(models.TextChoices):
        MORNING = 'Morning'
        AFTERNOON = 'Afternoon'

    title = models.CharField(max_length=100, blank=True, default="") # Most services will not actually have a title, they will be displayed on the schedule as the preacher's name
    schedule = models.ForeignKey(Schedule, null=True, blank=True, on_delete=models.CASCADE) # Delete all events in a schedule if schedule is deleted
    date = models.DateField()
    church = models.ForeignKey(Church, on_delete=models.CASCADE)
    preacher = models.ForeignKey(Preacher, null=True, blank=True,
                                 on_delete=models.SET_NULL)  # Field can be null when object is created
    service_type = models.CharField(
        max_length=9,
        choices=ServiceType.choices,
        default=ServiceType.MORNING,
    )

    def __str__(self):
        return str(self.id) + " | " + str(self.title) + " | " + str(self.date) + " | " + str(self.church) + " | " + str(self.preacher) + " | " + str(self.service_type)

schedule_calendar/forms.py
from django import forms
from schedule_calendar.models import Preacher, Church, Event
from bootstrap_datepicker_plus import DatePickerInput
from django.forms import modelformset_factory
from crispy_forms.helper import FormHelper

class PreacherUpdateForm(forms.ModelForm):
    first_name = forms.CharField()
    last_name = forms.CharField()
    phone_no = forms.CharField()
    email = forms.EmailField()
    num_services = forms.IntegerField()
    availability = forms.DateField(
        widget=DatePickerInput(
            options={
                "format": "mm/dd/yyyy",
            }
        )
    )

    class Meta:
        model = Preacher
        fields = ['first_name', 'last_name', 'phone_no', 'email', 'availability']


# This form is for the drop down cells on the schedule table
class EventUpdateForm(forms.ModelForm):
    title = forms.CharField(label='', required=False, widget=forms.TextInput(attrs={'placeholder': 'Details'}))
    preacher = forms.ModelChoiceField(queryset=Preacher.objects.all(), label='', required=False)
    # Have to send the other variables as hidden fields for validation purposes - definitely not best practice
    id = forms.IntegerField(widget=forms.HiddenInput())

    # self call to exclude preachers from the selectable list who are not available
    def __init__(self, *args, **kwargs):
        super(EventUpdateForm, self).__init__(*args, **kwargs)
        event = self.instance
        self.fields['preacher'].queryset = Preacher.objects.exclude(availability__contains=[event.date]).order_by('last_name')
        # crispy forms helper function for assigning classes etc. to forms
        self.helper = FormHelper()
        self.helper.form_class = 'cell-forms'

    # affects what happens when you call form.save() or formset.save()
    class Meta:
        model = Event
        fields = ['id', 'title', 'preacher']

    field_order = ['id', 'title', 'preacher']

schedule_calendar/templates/schedule_calendar/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'schedule_calendar/main.css' %}">
    {% if title %}
        <title>Church Scheduling System - {{ title }}</title>
    {% else %}
        <title>Church Scheduling System</title>
    {% endif %}
    <!-- Favicon -->
     <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>

    <!-- Optional JavaScript -->
    <script type="text/javascript" src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script type="text/javascript" src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="{% static 'schedule_calendar/Multiple-Dates-Picker-for-jQuery-UI-latest/jquery-ui.multidatespicker.js' %}" type="text/javascript"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script type="text/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'schedule_calendar/Multiple-Dates-Picker-for-jQuery-UI-latest/jquery-ui.multidatespicker.css' %}">
</head>
<body>
<header class="site-header">
    <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
            <a class="navbar-brand mr-4" href="{% url 'schedules' %}">Church Scheduling System</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggle">
                <div class="navbar-nav mr-auto">
                    <a class="nav-item nav-link" href="{% url 'schedules' %}">Schedule</a>
                    <a class="nav-item nav-link" href="{% url 'church_list' %}">Churches</a>
                    <a class="nav-item nav-link" href="{% url 'preacher_list' %}">Preachers</a>
                </div>
                <!-- Navbar Right Side -->
                <div class="navbar-nav">
                    {% if user.is_authenticated %}
                        <a class="nav-item nav-link" href="{% url 'profile' %}">Profile</a>
                        <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
                    {% else %}
                        <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
                        <a class="nav-item nav-link" href="{% url 'register' %}">Register</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </nav>
</header>
<main role="main" class="container">
    <!--any alerts will be displayed at the top of the page-->
    <div>
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}
        {% block content %}
        {% endblock %}
    </div>
</main>
</body>
</html>

schedule_calendar/templates/schedule_calendar/church_confirm_delete.html
<!--this template is shared for both creating and updating preachers-->
{% extends 'schedule_calendar/base.html' %}
{% block content %}
    <div class = "content-section">
        <form method = "POST" action="">
            {% csrf_token %}
            <fieldset class = "form-group">
                <legend class = "border-bottom mb-4">Delete Church</legend>
                <h2>Deleting {{ object.name }} will delete all past and future Events at this location. Are you sure?</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">
                    Confirm Deletion
                </button>
                <a class="btn btn-outline-secondary" href="{% url 'church_list' %}">
                    Cancel
                </a>
            </div>
        </form>
    </div>
{% endblock content %}

schedule_calendar/templates/schedule_calendar/church_form.html
<!--this template is shared for both creating and updating churches-->
{% extends 'schedule_calendar/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class = "content-section">
        <form method = "POST" action="">
            {% csrf_token %}
            <fieldset class = "form-group">
                <legend class = "border-bottom mb-4">Church Details</legend>
                {{ form|crispy }} <!--crispy forms is a bootstrap plugin that does a lot of the styling for you-->
            </fieldset>

            <div class="form-group">
                <button class="btn btn-info" type="submit">
                    Save
                </button>
                <button class="btn btn-outline-secondary" type="reset" onclick="javascript:history.back();">
                    Cancel
                </button>
            </div>
        </form>
    </div>
{% endblock content %}

schedule_calendar/templates/schedule_calendar/church_list.html
<!--This is how to specify a child template. The 'block content' in base.html will be overwritten with this-->
{% extends 'schedule_calendar/base.html' %}
{% block content %}
    <!--This is the syntax for accessing data which has been passed into a template-->
    <a class="btn btn-info mb-4" href="{% url 'church_form' %}">Create New Church</a>
    {% if is_paginated %}
        {% if page_obj.has_previous %}
            <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3'%}
                <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
        {% endif %}

    {% endif %}

    {% for church in churches %}
        <article class="media content-section">
            <div class="media-body">
                <h3>{{ church.name }}</h3>
                <p>Number: {{ church.number }}</p>
                <p>Address: {{ church.address }}</p>
                <a class="btn btn-outline-info" href="{% url 'church_update' church.id %}">Edit</a>
                <a class="btn btn-outline-danger" href="{% url 'church_delete' church.id %}">Delete</a>
            </div>
        </article>
    {% endfor %}
    <a class="btn btn-info mb-4" href="{% url 'church_form' %}">Create New Church</a>
    {% if is_paginated %}
        {% if page_obj.has_previous %}
            <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3'%}
                <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
        {% endif %}

    {% endif %}
{% endblock content %}

schedule_calendar/templates/schedule_calendar/event_confirm_delete.html
<!--this template is shared for both creating and updating preachers-->
{% extends 'schedule_calendar/base.html' %}
{% block content %}
    <div class = "content-section">
        <form method = "POST" action="">
            {% csrf_token %}
            <fieldset class = "form-group">
                <legend class = "border-bottom mb-4">Delete Event</legend>
                <h2>Are you sure you want to delete this event on {{ object.date }} at {{ object.church }}?</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">
                    Confirm Deletion
                </button>
                <a class="btn btn-outline-secondary" href="{% url 'event_list' %}">
                    Cancel
                </a>
            </div>
        </form>
    </div>
{% endblock content %}

schedule_calendar/templates/schedule_calendar/event_form.html
<!--this template is shared for both creating and updating events-->
{% extends 'schedule_calendar/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class = "content-section">
        <form method = "POST" action="">
            {% csrf_token %}
            <fieldset class = "form-group">
                <legend class = "border-bottom mb-4">Event Details</legend>
                {{ form|crispy }} <!--crispy forms is a bootstrap plugin that does a lot of the styling for you-->
            </fieldset>
            <div class="form-group">
                <button class="btn btn-info" type="submit">
                    Save
                </button>
                <button class="btn btn-outline-secondary" type="reset" onclick="javascript:history.back();">
                    Cancel
                </button>
            </div>
        </form>
    </div>
{% endblock content %}

schedule_calendar/templates/schedule_calendar/event_list.html
<!--This is how to specify a child template. The 'block content' in base.html will be overwritten with this-->
{% extends 'schedule_calendar/base.html' %}
{% block content %}
    <!--This is the syntax for accessing data which has been passed into a template-->
    {% for event in events %}
        <article class="media content-section">
          <div class="media-body">
              <h3>{{ event.title }}</h3>
              <p>Schedule: {{ event.schedule }}</p>
              <p>Date: {{ event.date }}</p>
              <p>Church: {{ event.church }}</p>
              <p>Preacher: {{ event.preacher }}</p>
              <p>Service Type: {{ event.service_type }}</p>
              <a class="btn btn-outline-info" href="{% url 'event_update' event.id %}">Edit</a>
              <a class="btn btn-outline-danger" href="{% url 'event_delete' event.id %}">Delete</a>
          </div>
        </article>
    {% endfor %}
    <a class="btn btn-info mb-4" href="{% url 'event_form' %}">Create New Event</a>
    {% if is_paginated %}
        {% if page_obj.has_previous %}
            <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
                {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3'%}
                <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
        {% endif %}

    {% endif %}
{% endblock content %}

schedule_calendar/templates/schedule_calendar/preacher_confirm_delete.html
<!--this template is shared for both creating and updating preachers-->
{% extends 'schedule_calendar/base.html' %}
{% block content %}
    <div class = "content-section">
        <form method = "POST" action="">
            {% csrf_token %}
            <fieldset class = "form-group">
                <legend class = "border-bottom mb-4">Delete Preacher</legend>
                <h2>Are you sure you want to delete {{ object.first_name }} {{ object.last_name }}?</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">
                    Confirm Deletion
                </button>
                <a class="btn btn-outline-secondary" href="{% url 'preacher_list' %}">
                    Cancel
                </a>
            </div>
        </form>
    </div>
{% endblock content %}

schedule_calendar/templates/schedule_calendar/schedule_form.html
{% extends 'schedule_calendar/schedule_base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <!--This is the big front-end table for the schedule form. This is where a user will spend most of their time-->
    <div class="table-responsive">
        <div class="table-area">
            <form action="" method="POST">
                {{ formset.management_form }}
                {% csrf_token %}
                <table class="responsive-table table table-bordered" id="table-1">
                    <thead>
                    <tr>
                        <th colspan="3">{{ schedule }}
                            <input type="submit" class="btn btn-info btn-sm" name="save" value="Save" formmethod="POST">
                            <input type="submit" class="btn btn-info btn-sm" name="auto_schedule" value="Schedule">
                            <input type="button" class="btn btn-info btn-sm" name="print" value="Print" onclick="window.print();return false;">
                            <input type="button" class="btn btn-info btn-sm" name="export" value="Export" id="export" onclick="table2excel();">
                        </th>
                        {% for month, length in schedule.months.items %}
                            <th colspan="{{ length }}">{{ month }}</th>
                        {% endfor %}
                    </tr>
                    <tr>
                        <th scope="col">Church</th>
                        <th scope="col">Number</th>
                        <th scope="col">Time</th>
                        {% for date in schedule.dates %}
                            <th>{{ date }}</th>
                        {% endfor %}
                    </tr>
                    </thead>
                    <tbody>
                    {% for church in churches %}
                        <tr>
                            <td rowspan="2" class="row-titles">{{ church }}</td>
                            <td rowspan="2" class="row-titles" style="margin-right: -1px;">{{ church.number }}</td>
                            <td class="row-titles border-right">
                                {% if church.morning_service_time != None %}
                                    {{ church.morning_service_time }}
                                {% endif %}
                            </td>
                            {% for event in events %}
                                {% if event.church == church and event.service_type == 'Morning' %}
                                    <td class="align-middle">
                                        <a href="javascript:void(0)" class="edit" id="{{ event.id }}">
                                            <div class="table-select">
                                                {% if event.title != "" %}
                                                    {{ event.title }}
                                                    <br>
                                                {% endif %}
                                                {% if event.title != "No Service" %}
                                                    {{ event.preacher }}
                                                {% endif %}
                                            </div>
                                        </a>
                                    </td>
                                {% endif %}
                            {% endfor %}
                        </tr>
                        <tr>
                        <td class="row-titles border-right">
                            {% if church.afternoon_service_time != None %}
                                {{ church.afternoon_service_time }}
                            {% endif %}
                        </td>
                        {% for event in events %}
                            {% if event.church == church and event.service_type == 'Afternoon' %}
                                <td class="align-middle">
                                    <a href="javascript:void(0)" class="edit" id="{{ event.id }}">
                                        {% if event.title != "" %}
                                            {{ event.title }}
                                            <br>
                                        {% endif %}
                                        {% if event.title != "No Service" %}
                                            {{ event.preacher }}
                                        {% endif %}
                                    </a>
                                </td>
                            {% endif %}
                        {% endfor %}
                    {% endfor %}
                    </tr>
                    </tbody>
                </table>
            </form>
        </div>
    </div>

    <script type="text/javascript">
        $(document).ready(function(e) {
            $( "#export" ).click(function() {
                $("#table-1").table2excel({
                    exclude: ".noExport",
                    name: "{{ schedule }}",
                    filename: "{{ schedule }}",
                    fileext: ".xls",
                    exclude_links: true,
                    exclude_inputs: true,
                });
            });

            var form_count = {{formset.total_form_count}};

            $('.edit').dblclick(function() {
                var link = this
                var event_id = $(this).attr("id")
                $.ajax({
                    url : "{% url 'get_form' %}", // the endpoint
                    type : "GET", // http method
                    data : { event_id : event_id }, // data sent with the post request

                    // Handle a successful response. TODO: If I have time, move the form logic to the view endpoint
                    success : function(form) {
                        form_count++
                        var id_num = form_count-1
                        $( link ).replaceWith(form);
                        $('#id_form-TOTAL_FORMS').val(form_count);
                        $('#id_form-INITIAL_FORMS').val(form_count);
                        $('#id_title').attr('name', 'form-' + id_num + '-title');
                        $('#id_title').attr('id', 'id_form-' + id_num + '-title');
                        $('#id_preacher').attr('name', 'form-' + id_num + '-preacher');
                        $('#id_preacher').attr('id', 'id_form-' + id_num + '-preacher');
                        $('#id_id').attr('name', 'form-' + id_num + '-id');
                        $('#id_id').attr('id', 'id_form-' + id_num + '-id');
                    },

                    // handle a non-successful response
                    error : function(xhr,errmsg,err) {
                        $('#results').html("<div class='alert-box alert radius' data-alert>AJAX has encountered an error: "+errmsg+
                            " <a href='#' class='close'>&times;</a></div>"); // add the error to the dom
                        console.log(xhr.status + ": " + xhr.responseText); // provide a bit more info about the error to the console
                    }
                });
            });
        });
    </script>
{% endblock content %}